package pagamento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marília
 */
public class InterfacePagamento extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePagamento
     */
    public InterfacePagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelModalPagamento = new javax.swing.JLabel();
        labelQtdParcelas = new javax.swing.JLabel();
        selectModalPagamento = new javax.swing.JComboBox<>();
        selectQtdParcelas = new javax.swing.JComboBox<>();
        btnConfirmarModoPagamento = new javax.swing.JButton();
        labelPagamento = new javax.swing.JLabel();
        labelTaxaEmReal = new javax.swing.JLabel();
        labelValorLiq = new javax.swing.JLabel();
        txtTaxaPercent = new javax.swing.JLabel();
        txtTaxaEmReal = new javax.swing.JLabel();
        txtValorLiq = new javax.swing.JLabel();
        labelTaxaPercent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelModalPagamento.setText("Modo de Pagamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 115, 0, 0);
        getContentPane().add(labelModalPagamento, gridBagConstraints);

        labelQtdParcelas.setText("Parcelas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 115, 0, 0);
        getContentPane().add(labelQtdParcelas, gridBagConstraints);

        selectModalPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Débito", "Crédito", "Crédito Parcelado" }));
        selectModalPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectModalPagamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 4, 0, 10);
        getContentPane().add(selectModalPagamento, gridBagConstraints);

        selectQtdParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "2x", "3x" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        getContentPane().add(selectQtdParcelas, gridBagConstraints);

        btnConfirmarModoPagamento.setText("Calcular");
        btnConfirmarModoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarModoPagamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 115, 118, 0);
        getContentPane().add(btnConfirmarModoPagamento, gridBagConstraints);

        labelPagamento.setText("Selecione a opção de pagamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 55, 0, 0);
        getContentPane().add(labelPagamento, gridBagConstraints);

        labelTaxaEmReal.setText("Taxa a Pagar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 109, 0, 0);
        getContentPane().add(labelTaxaEmReal, gridBagConstraints);

        labelValorLiq.setText("Valor Líquido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 109, 0, 0);
        getContentPane().add(labelValorLiq, gridBagConstraints);

        txtTaxaPercent.setText("-- %");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(txtTaxaPercent, gridBagConstraints);

        txtTaxaEmReal.setText("R$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        getContentPane().add(txtTaxaEmReal, gridBagConstraints);

        txtValorLiq.setText("R$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(txtValorLiq, gridBagConstraints);

        labelTaxaPercent.setText("Taxa (%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 109, 0, 0);
        getContentPane().add(labelTaxaPercent, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectModalPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectModalPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectModalPagamentoActionPerformed

    private void btnConfirmarModoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarModoPagamentoActionPerformed
        String value = (String)selectModalPagamento.getSelectedItem();
        
        if (null != value) switch (value) {
            case "Débito":{
                ModalCredito pagamento = new ModalCredito();
                    break;
                }
            case "Crédito":{
                ModalRotativo pagamento = new ModalRotativo();
                    break;
                }
            case "Crédito Parcelado":{
                ModalParcelado pagamento = new ModalParcelado();
                    break;
                }
            default:
                break;
        }
        
        
    }//GEN-LAST:event_btnConfirmarModoPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarModoPagamento;
    private javax.swing.JLabel labelModalPagamento;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JLabel labelQtdParcelas;
    private javax.swing.JLabel labelTaxaEmReal;
    private javax.swing.JLabel labelTaxaPercent;
    private javax.swing.JLabel labelValorLiq;
    private javax.swing.JComboBox<String> selectModalPagamento;
    private javax.swing.JComboBox<String> selectQtdParcelas;
    private javax.swing.JLabel txtTaxaEmReal;
    private javax.swing.JLabel txtTaxaPercent;
    private javax.swing.JLabel txtValorLiq;
    // End of variables declaration//GEN-END:variables
}
