package cartao;


import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marília
 */
public class InterfaceCartao extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceCartao
     */
    public InterfaceCartao() {
        initComponents();
        selectBandeira.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAddCartao = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        selectBandeira = new javax.swing.JComboBox<>();
        labelNumbCartao = new javax.swing.JLabel();
        labelNomeImpressoCartao = new javax.swing.JLabel();
        labelValidade = new javax.swing.JLabel();
        labelCvv = new javax.swing.JLabel();
        labelBandeira = new javax.swing.JLabel();
        labelInstituicaoFinanceira = new javax.swing.JLabel();
        labelIdComprador = new javax.swing.JLabel();
        inputCvv = new javax.swing.JTextField();
        inputIdComprador = new javax.swing.JTextField();
        inputIdInstituicaoFinanceira = new javax.swing.JTextField();
        inputNomeImpressoCartao = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        inputNumbCartao = new javax.swing.JFormattedTextField();
        btnAddCartao = new javax.swing.JButton();
        jFormattedTextFieldDATAexpira = new javax.swing.JFormattedTextField();
        jTextFieldSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAddCartao.setText("Adicione um Cartão");

        selectBandeira.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "visa", "master card", "hipercard", "elo" }));
        selectBandeira.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectBandeiraItemStateChanged(evt);
            }
        });
        selectBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBandeiraActionPerformed(evt);
            }
        });

        labelNumbCartao.setText("Número do Cartão");

        labelNomeImpressoCartao.setText("Nome no Cartão");

        labelValidade.setText("Data de expiração");

        labelCvv.setText("Código CVV");

        labelBandeira.setText("Bandeira");

        labelInstituicaoFinanceira.setText("Instituicao Financeira");

        labelIdComprador.setText("Id Comprador");

        inputIdInstituicaoFinanceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdInstituicaoFinanceiraActionPerformed(evt);
            }
        });

        labelSenha.setText("Senha");

        try {
            inputNumbCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.####.####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAddCartao.setText("Adicionar");
        btnAddCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartaoActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDATAexpira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDATAexpira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDATAexpiraActionPerformed(evt);
            }
        });

        jTextFieldSenha.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCvv)
                            .addComponent(labelNumbCartao)
                            .addComponent(labelBandeira)
                            .addComponent(labelInstituicaoFinanceira)
                            .addComponent(labelIdComprador)
                            .addComponent(labelNomeImpressoCartao)
                            .addComponent(labelValidade)
                            .addComponent(labelSenha))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnAddCartao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldDATAexpira, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNumbCartao, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(inputIdInstituicaoFinanceira)
                                    .addComponent(inputCvv)
                                    .addComponent(inputIdComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNomeImpressoCartao)
                                    .addComponent(jTextFieldSenha))
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelAddCartao)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelAddCartao)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(selectBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBandeira)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInstituicaoFinanceira)
                    .addComponent(inputIdInstituicaoFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumbCartao)
                    .addComponent(inputNumbCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCvv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValidade)
                    .addComponent(jFormattedTextFieldDATAexpira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdComprador)
                    .addComponent(inputIdComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeImpressoCartao)
                    .addComponent(inputNomeImpressoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSenha)
                    .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCartao)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBandeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBandeiraActionPerformed

    private void inputIdInstituicaoFinanceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdInstituicaoFinanceiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdInstituicaoFinanceiraActionPerformed

    private void btnAddCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartaoActionPerformed
        
        try {
            
            
            CartaoDeCredito cartao = new CartaoDeCredito();
            
           
            
            
            
            String dataString = jFormattedTextFieldDATAexpira.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
              
            cartao.setValidade(data);
            cartao.setNumbCartao(inputNumbCartao.getText());
            cartao.setNomeImpressoCartao(inputNomeImpressoCartao.getText());
            cartao.setCvv(inputCvv.getText());
            cartao.setBandeira(selectBandeira.getSelectedItem().toString());  //?????
            cartao.setSenha(jTextFieldSenha.getText());
            cartao.getComprador().setIdComprador(Integer.parseInt(inputIdComprador.getText()));
            cartao.getInstituicaoFinanceira().setIdInstituicaoFinanceira(Integer.parseInt(inputIdInstituicaoFinanceira.getText()));
            
            
            
            CartaoNegocios dados = new CartaoNegocios();
            dados.CadastrarCartao(cartao);
            
            
            JOptionPane.showMessageDialog(null,"Cartão cadastrado com sucesso."); 
        } catch (Exception e) {
         JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}


    }//GEN-LAST:event_btnAddCartaoActionPerformed

    private void selectBandeiraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectBandeiraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBandeiraItemStateChanged

    private void jFormattedTextFieldDATAexpiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDATAexpiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDATAexpiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCartao;
    private javax.swing.JTextField inputCvv;
    private javax.swing.JTextField inputIdComprador;
    private javax.swing.JTextField inputIdInstituicaoFinanceira;
    private javax.swing.JTextField inputNomeImpressoCartao;
    private javax.swing.JFormattedTextField inputNumbCartao;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JFormattedTextField jFormattedTextFieldDATAexpira;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JLabel labelAddCartao;
    private javax.swing.JLabel labelBandeira;
    private javax.swing.JLabel labelCvv;
    private javax.swing.JLabel labelIdComprador;
    private javax.swing.JLabel labelInstituicaoFinanceira;
    private javax.swing.JLabel labelNomeImpressoCartao;
    private javax.swing.JLabel labelNumbCartao;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelValidade;
    private javax.swing.JComboBox<String> selectBandeira;
    // End of variables declaration//GEN-END:variables
}
