/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marília
 */
public class Maquineta extends javax.swing.JFrame {

    /**
     * Creates new form MaquinaCartao
     */
    public Maquineta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnN1 = new javax.swing.JButton();
        btnN2 = new javax.swing.JButton();
        btnN3 = new javax.swing.JButton();
        btnN4 = new javax.swing.JButton();
        btnN5 = new javax.swing.JButton();
        btnN6 = new javax.swing.JButton();
        btnN7 = new javax.swing.JButton();
        btnN8 = new javax.swing.JButton();
        btnN9 = new javax.swing.JButton();
        btnAsterisco = new javax.swing.JButton();
        btnNzero = new javax.swing.JButton();
        btnCerquilha = new javax.swing.JButton();
        btnAnula = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        btnEntra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnN1.setBackground(new java.awt.Color(51, 51, 51));
        btnN1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN1.setForeground(new java.awt.Color(255, 255, 255));
        btnN1.setText("1");
        btnN1.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN1, gridBagConstraints);

        btnN2.setBackground(new java.awt.Color(51, 51, 51));
        btnN2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN2.setForeground(new java.awt.Color(255, 255, 255));
        btnN2.setText("2");
        btnN2.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN2, gridBagConstraints);

        btnN3.setBackground(new java.awt.Color(51, 51, 51));
        btnN3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN3.setForeground(new java.awt.Color(255, 255, 255));
        btnN3.setText("3");
        btnN3.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN3, gridBagConstraints);

        btnN4.setBackground(new java.awt.Color(51, 51, 51));
        btnN4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN4.setForeground(new java.awt.Color(255, 255, 255));
        btnN4.setText("4");
        btnN4.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN4, gridBagConstraints);

        btnN5.setBackground(new java.awt.Color(51, 51, 51));
        btnN5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN5.setForeground(new java.awt.Color(255, 255, 255));
        btnN5.setText("5");
        btnN5.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN5, gridBagConstraints);

        btnN6.setBackground(new java.awt.Color(51, 51, 51));
        btnN6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN6.setForeground(new java.awt.Color(255, 255, 255));
        btnN6.setText("6");
        btnN6.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN6, gridBagConstraints);

        btnN7.setBackground(new java.awt.Color(51, 51, 51));
        btnN7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN7.setForeground(new java.awt.Color(255, 255, 255));
        btnN7.setText("7");
        btnN7.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN7, gridBagConstraints);

        btnN8.setBackground(new java.awt.Color(51, 51, 51));
        btnN8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN8.setForeground(new java.awt.Color(255, 255, 255));
        btnN8.setText("8");
        btnN8.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN8, gridBagConstraints);

        btnN9.setBackground(new java.awt.Color(51, 51, 51));
        btnN9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnN9.setForeground(new java.awt.Color(255, 255, 255));
        btnN9.setText("9");
        btnN9.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnN9, gridBagConstraints);

        btnAsterisco.setBackground(new java.awt.Color(51, 51, 51));
        btnAsterisco.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnAsterisco.setForeground(new java.awt.Color(255, 255, 255));
        btnAsterisco.setText("*");
        btnAsterisco.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnAsterisco, gridBagConstraints);

        btnNzero.setBackground(new java.awt.Color(51, 51, 51));
        btnNzero.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnNzero.setForeground(new java.awt.Color(255, 255, 255));
        btnNzero.setText("0");
        btnNzero.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnNzero, gridBagConstraints);

        btnCerquilha.setBackground(new java.awt.Color(51, 51, 51));
        btnCerquilha.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        btnCerquilha.setForeground(new java.awt.Color(255, 255, 255));
        btnCerquilha.setText("#");
        btnCerquilha.setMargin(new java.awt.Insets(4, 30, 4, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnCerquilha, gridBagConstraints);

        btnAnula.setBackground(new java.awt.Color(255, 0, 0));
        btnAnula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAnula.setForeground(new java.awt.Color(255, 255, 255));
        btnAnula.setText("ANULA");
        btnAnula.setMargin(new java.awt.Insets(10, 20, 10, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnAnula, gridBagConstraints);

        btnLimpa.setBackground(new java.awt.Color(255, 204, 0));
        btnLimpa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpa.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpa.setText("LIMPA");
        btnLimpa.setMargin(new java.awt.Insets(10, 20, 10, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnLimpa, gridBagConstraints);

        btnEntra.setBackground(new java.awt.Color(0, 153, 0));
        btnEntra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntra.setForeground(new java.awt.Color(255, 255, 255));
        btnEntra.setText("ENTRA");
        btnEntra.setMargin(new java.awt.Insets(10, 20, 10, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnEntra, gridBagConstraints);

        jTextArea1.setColumns(15);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maquineta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maquineta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maquineta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maquineta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maquineta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnula;
    private javax.swing.JButton btnAsterisco;
    private javax.swing.JButton btnCerquilha;
    private javax.swing.JButton btnEntra;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnN1;
    private javax.swing.JButton btnN2;
    private javax.swing.JButton btnN3;
    private javax.swing.JButton btnN4;
    private javax.swing.JButton btnN5;
    private javax.swing.JButton btnN6;
    private javax.swing.JButton btnN7;
    private javax.swing.JButton btnN8;
    private javax.swing.JButton btnN9;
    private javax.swing.JButton btnNzero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
